In [3]:
import requests
import os
import json
import pandas as pd

In [2]:
#A file containing your api key obtained from the website - https://oikolab.com/
with open("keyfile_tanya.txt") as f:
    api_key = f.readlines()[0].rstrip()

In [48]:
r = requests.get('https://api.oikolab.com/weather',
                 params={'param': ['temperature',  
                                   'relative_humidity', 
                                    'humidex', 
                                    'surface_solar_radiation', 
                                    'surface_thermal_radiation', 
                                    'surface_direct_solar_radiation', 
                                    'wind_speed', 'wind_direction',
                                    'soil_temperature_level_1', 
                                    'soil_temperature_level_2', 
                                    'soil_temperature_level_3', 
                                    'soil_temperature_level_4', 
                                    'total_precipitation'],
                         'start': '2014-01-01',
                         'end': '2016-12-31',
                         'lat': 14.6937,
                         'lon': -17.44406,
                         'api-key': api_key}
                )

In [49]:
r

'relative_humidity', 
                                    'humidex', 
                                    'surface_solar_radiation', 
                                    'surface_thermal_radiation', 
                                    'surface_direct_solar_radiation', 
                                    'wind_speed', 'wind_direction',

In [35]:
weather_data = json.loads(r.json()['data'])

df = pd.DataFrame(index=pd.to_datetime(weather_data['index'], 
                                       unit='s'),
                  data=weather_data['data'],
                  columns=weather_data['columns'])

In [36]:
df

,temperature (degC),relative_humidity (0-1),humidex (degC),surface_solar_radiation (W/m^2),surface_thermal_radiation (W/m^2),surface_direct_solar_radiation (W/m^2),wind_speed (m/s),wind_direction (deg),soil_temperature_level_1 (degC),soil_temperature_level_2 (degC),soil_temperature_level_3 (degC),soil_temperature_level_4 (degC),total_precipitation (mm of water equivalent)
2014-01-01 00:00:00,20.33,0.84,26.01,0,323,-0.04,4.85,5.06,20.19,20.82,20.96,21.21,0.0
2014-01-01 01:00:00,20.29,0.84,25.89,0,322,-0.04,4.79,6.02,20.10,20.79,20.96,21.21,0.0
2014-01-01 02:00:00,20.34,0.83,25.88,0,322,-0.04,4.85,5.55,20.10,20.77,20.96,21.21,0.0
2014-01-01 03:00:00,20.39,0.82,25.88,0,321,-0.04,4.84,8.22,20.09,20.75,20.96,21.21,0.0
2014-01-01 04:00:00,20.38,0.81,25.73,0,321,-0.04,4.89,17.33,19.99,20.72,20.96,21.21,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-30 20:00:00,24.28,0.60,28.85,0,338,-0.04,5.71,33.11,22.74,22.93,22.85,23.01,0.0
2016-12-30 21:00:00,24.34,0.57,28.55,0,338,-0.04,5.39,33.16,22.58,22.92,22.85,23.01,0.0
2016-12-30 22:00:00,24.36,0.55,28.16,0,337,-0.04,5.17,40.59,22.54,22.91,22.85,23.01,0.0
2016-12-30 23:00:00,24.41,0.52,27.72,0,336,-0.04,5.20,47.72,22.54,22.89,22.86,23.01,0.0
2016-12-31 00:00:00,24.35,0.49,27.17,0,334,-0.04,5.24,58.00,22.53,22.87,22.86,23.01,0.0

In [14]:
raw = df.rename(columns = {
      'temperature (degC)':'temp',
      'relative_humidity (0-1)':'rel_hum',
      'humidex (degC)':'hum',
      'wind_speed (m/s)':'wind_speed',
      'wind_direction (deg)':'wind_dir',
      'surface_solar_radiation (W/m^2)':'solar_radiat',
      'surface_thermal_radiation (W/m^2)':'thermal_radiat',
      'surface_direct_solar_radiation (W/m^2)':'dir_solar_radiat',
      'urban_temperature (degC)':'urban_temp',
      'soil_temperature_level_1 (degC)':'soil_1',
      'soil_temperature_level_2 (degC)':'soil_2',
      'soil_temperature_level_3 (degC)':'soil_3',
      'soil_temperature_level_4 (degC)':'soil_4',
      'total_precipitation (mm of water equivalent)':'pr'
  })

In [32]:
raw.index.day
#this is the datetime col

Int64Index([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
            ...
            30, 30, 30, 30, 30, 30, 30, 30, 30, 31],
           dtype='int64', length=184081)

In [37]:
raw

,temp,rel_hum,hum,solar_radiat,thermal_radiat,dir_solar_radiat,wind_speed,wind_dir,soil_1,soil_2,soil_3,soil_4,pr
2000-01-01 00:00:00,20.66,0.85,26.68,0,333,-0.04,6.77,343.28,21.47,22.07,22.22,22.49,0.0
2000-01-01 01:00:00,20.53,0.85,26.54,0,333,-0.04,6.90,344.59,21.39,22.05,22.22,22.49,0.0
2000-01-01 02:00:00,20.45,0.86,26.44,0,341,-0.04,7.26,347.13,21.33,22.03,22.22,22.49,0.0
2000-01-01 03:00:00,20.43,0.86,26.47,0,342,-0.04,7.37,350.61,21.34,22.01,22.22,22.49,0.0
2000-01-01 04:00:00,20.33,0.86,26.34,0,348,-0.04,7.17,354.50,21.32,21.99,22.22,22.49,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-30 20:00:00,22.60,0.83,29.84,0,361,-0.04,8.08,6.05,22.17,22.33,22.24,22.42,0.0
2020-12-30 21:00:00,22.62,0.84,30.04,0,363,-0.04,8.24,4.44,21.24,22.32,22.24,22.42,0.0
2020-12-30 22:00:00,22.61,0.84,29.98,0,361,-0.04,8.05,7.35,21.19,22.31,22.24,22.42,0.0
2020-12-30 23:00:00,22.59,0.83,29.84,0,359,-0.04,8.00,9.76,21.15,22.28,22.24,22.42,0.0
2020-12-31 00:00:00,22.58,0.83,29.73,0,357,-0.04,7.97,10.98,21.13,22.27,22.24,22.42,0.0

In [40]:
raw["year"] = raw.index.year

In [42]:
raw["month"] = raw.index.month

In [43]:
raw["day"] = raw.index.day

In [44]:
raw["hour"] = raw.index.hour

In [45]:
raw

,temp,rel_hum,hum,solar_radiat,thermal_radiat,dir_solar_radiat,wind_speed,wind_dir,soil_1,soil_2,soil_3,soil_4,pr,year,month,day,hour
2000-01-01 00:00:00,20.66,0.85,26.68,0,333,-0.04,6.77,343.28,21.47,22.07,22.22,22.49,0.0,2000,1,1,0
2000-01-01 01:00:00,20.53,0.85,26.54,0,333,-0.04,6.90,344.59,21.39,22.05,22.22,22.49,0.0,2000,1,1,1
2000-01-01 02:00:00,20.45,0.86,26.44,0,341,-0.04,7.26,347.13,21.33,22.03,22.22,22.49,0.0,2000,1,1,2
2000-01-01 03:00:00,20.43,0.86,26.47,0,342,-0.04,7.37,350.61,21.34,22.01,22.22,22.49,0.0,2000,1,1,3
2000-01-01 04:00:00,20.33,0.86,26.34,0,348,-0.04,7.17,354.50,21.32,21.99,22.22,22.49,0.0,2000,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-30 20:00:00,22.60,0.83,29.84,0,361,-0.04,8.08,6.05,22.17,22.33,22.24,22.42,0.0,2020,12,30,20
2020-12-30 21:00:00,22.62,0.84,30.04,0,363,-0.04,8.24,4.44,21.24,22.32,22.24,22.42,0.0,2020,12,30,21
2020-12-30 22:00:00,22.61,0.84,29.98,0,361,-0.04,8.05,7.35,21.19,22.31,22.24,22.42,0.0,2020,12,30,22
2020-12-30 23:00:00,22.59,0.83,29.84,0,359,-0.04,8.00,9.76,21.15,22.28,22.24,22.42,0.0,2020,12,30,23
2020-12-31 00:00:00,22.58,0.83,29.73,0,357,-0.04,7.97,10.98,21.13,22.27,22.24,22.42,0.0,2020,12,31,0

In [46]:
raw["gpslat"] = 14.6937
raw["gpslon"] = -17.44406

In [47]:
raw

,temp,rel_hum,hum,solar_radiat,thermal_radiat,dir_solar_radiat,wind_speed,wind_dir,soil_1,soil_2,soil_3,soil_4,pr,year,month,day,hour,gpslat,gpslon
2000-01-01 00:00:00,20.66,0.85,26.68,0,333,-0.04,6.77,343.28,21.47,22.07,22.22,22.49,0.0,2000,1,1,0,14.6937,-17.44406
2000-01-01 01:00:00,20.53,0.85,26.54,0,333,-0.04,6.90,344.59,21.39,22.05,22.22,22.49,0.0,2000,1,1,1,14.6937,-17.44406
2000-01-01 02:00:00,20.45,0.86,26.44,0,341,-0.04,7.26,347.13,21.33,22.03,22.22,22.49,0.0,2000,1,1,2,14.6937,-17.44406
2000-01-01 03:00:00,20.43,0.86,26.47,0,342,-0.04,7.37,350.61,21.34,22.01,22.22,22.49,0.0,2000,1,1,3,14.6937,-17.44406
2000-01-01 04:00:00,20.33,0.86,26.34,0,348,-0.04,7.17,354.50,21.32,21.99,22.22,22.49,0.0,2000,1,1,4,14.6937,-17.44406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-30 20:00:00,22.60,0.83,29.84,0,361,-0.04,8.08,6.05,22.17,22.33,22.24,22.42,0.0,2020,12,30,20,14.6937,-17.44406
2020-12-30 21:00:00,22.62,0.84,30.04,0,363,-0.04,8.24,4.44,21.24,22.32,22.24,22.42,0.0,2020,12,30,21,14.6937,-17.44406
2020-12-30 22:00:00,22.61,0.84,29.98,0,361,-0.04,8.05,7.35,21.19,22.31,22.24,22.42,0.0,2020,12,30,22,14.6937,-17.44406
2020-12-30 23:00:00,22.59,0.83,29.84,0,359,-0.04,8.00,9.76,21.15,22.28,22.24,22.42,0.0,2020,12,30,23,14.6937,-17.44406
2020-12-31 00:00:00,22.58,0.83,29.73,0,357,-0.04,7.97,10.98,21.13,22.27,22.24,22.42,0.0,2020,12,31,0,14.6937,-17.44406